### ISSUE TITLE
Mention the need for permissions

### ISSUE THREAD

**Issue by jamessan** [zeebe-io/backport-action#189]
As recommended by GitHub, I've set read-only permissions for actions by default.  This was preventing backport-action from working, since it needs to be able to create commits/PRs and therefore needs:

```yml
    permissions:
      contents: write
      pull-requests: write
```
